### ISSUE TITLE
Add examples to README

### ISSUE THREAD

**Issue by hueniverse** [hapijs/podium#4]

**Comment by rahuljain1311** [comment]
There is a typo in `API.md` file. Also I have added examples to README.md file but I don't have push access.

**Comment by hueniverse** [comment]
@rahuljain1311 you should read on how to fork a repo and submit a pull request.

**Comment by rahuljain1311** [comment]
should we close this issue or do you need a more exhaustive README?

**Comment by hueniverse** [comment]
The examples I want added are more of a cookbook. Show how to use the different options.

**Comment by rahuljain1311** [comment]
@hueniverse can you please see the PR and suggest improvements(if any).
