### ISSUE TITLE
Remove "podium" event source

### ISSUE THREAD

**Issue by kanongil** [hapijs/podium#65]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: any
* *module version*: 4.x
* *environment* (e.g. node, browser, native): any
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*:

#### What problem are you trying to solve?

Simpler module maintenance. Completely avoids the issue in #64.

#### Do you have a new or modified API suggestion to solve the problem?

Remove `podium.registerPodium()` method, and the Podium argument handling from constructor and `podium. registerEvent()`.

There is no direct usage of this feature inside the hapijs ecosystem. It is however exposed through [`server.events()`](https://hapi.dev/api/?v=20.0.0#-servereventevents) in hapi, so that support would need to go as well. This feature is already problematic, as it requires the caller to use the exact same instance of the Podium module, as hapi itself. Otherwise it will fail the `instanceof` check, and be treated as an event object.

There might also be another bug in the feature, where late event registrations are not handled.

**Comment by hueniverse** [comment]
This was used in hapi for a while. If it is no longer used, I see no reason to keep it.
