### ISSUE TITLE
Don't return promise from emit()

### ISSUE THREAD

**Issue by kanongil** [hapijs/podium#73]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: n/a
* *module version*: 4.1.3
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi / standalone
* *any other relevant information*:

#### What problem are you trying to solve?

hapijs/hapi#4184

#### Do you have a new or modified API suggestion to solve the problem?

Don't return promise from emit() and don't wait for listeners.

**Comment by Marsup** [comment]
IIRC that was intentional, didn't you find any use for that?

**Comment by kanongil** [comment]
Yes, it is used by hapi for server start and stop events. However, it is redundant (eg. there is an onPostStart handler), and the feature as a whole is rather dumb. Why have a system that lets fire-and-forget event subscribers slow you down significantly?

**Comment by Marsup** [comment]
I was rather thinking about userland calls where you might want to wait for all handlers to have executed. Hapi could be seen as a generic event emitter by some.

**Comment by kanongil** [comment]
That’s why it is a breaking change. Anyway, why would it be used in userland? There is no documentation for the feature, other than in the typings. And it’s still a dumb feature. You should not allow event listeners to async delay your main logic, that is what hooks are for.

Removing the feature means that all emits will be much more efficient, and we will have less code to maintain.

If you really feel that there is a usecase here, it can always be enabled as an event option.

**Comment by Marsup** [comment]
I can't remember why we did it at the time but I remember it made sense, maybe it doesn't anymore. Eran shall have a better recollection of the reasons, issues of why it was introduced don't mention anything.

**Comment by kanongil** [comment]
Maybe it was just caught up in the "async everything" transition, without any deeper thought into if it was a meaningful feature?

**Comment by hueniverse** [comment]
I don't remember the history of this feature, just that I have used this pattern myself where I replaced a sync emitter with this and wanted to end up with the same guarantee that when `emit()` returns all the handlers finished. Why not just change it to return a `Promise.all()` of the array or results or even just the array of results? This will keep the feature with minimal breakage but should improve performance.

**Comment by kanongil** [comment]
`Promise.all()` of the results is essentially how it works right now, except that thrown errors are converted to rejections.

An simple array of the results could work, enabling the user to call `Promise.all()` on the result of the emit, if desired. You could also handle thrown errors with a try/catch, though this can only handle one error, where the existing implementation returns every one as rejections.

Personally, I would like to keep it simple and aligned with what people expect from an event emitter `emit()` call.

If we really desire to support waiting for the results, I propose to add a new method for this. Maybe a `gauge()` method, to fit with the podium metaphor. This way we can keep the standard `emit()` logic mean and clean.

**Comment by hueniverse** [comment]
Adding `gauge()` work for me.
